# Generated by Django 5.2.1 on 2025-05-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('preco', models.FloatField(max_length=200)),
                ('mesa', models.IntegerField(max_length=200)),
                ('garcom', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
