# Generated by Django 5.2.1 on 2025-05-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garcom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField(max_length=15)),
                ('sexo', models.CharField(max_length=15)),
                ('foto', models.CharField(max_length=254)),
            ],
        ),
    ]
