# Generated by Django 5.2.1 on 2025-05-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garcom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField()),
                ('cpf', models.CharField()),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField()),
                ('foto', models.CharField()),
            ],
        ),
    ]
