# Generated by Django 5.2.1 on 2025-05-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garcom', '0002_alter_garcom_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garcom',
            name='cpf',
            field=models.CharField(max_length=253),
        ),
        migrations.AlterField(
            model_name='garcom',
            name='sexo',
            field=models.CharField(max_length=252),
        ),
    ]
